### ISSUE TITLE
Updating rapiclient on CRAN

### ISSUE THREAD

**Issue by LiNk-NY** [bergant/rapiclient#13]
Dear Darko, @bergant 

Thank you for creating this utility for importing swagger APIs into R. 

Your package has gone through a number of improvements with the help of
Martin @mtmorgan 's fork on https://github.com/Bioconductor/AnVIL_rapiclient. You can see the comparison here: https://github.com/bergant/rapiclient/compare/master...Bioconductor:master

It would be great if you could update the current version of `rapiclient` on CRAN
so that we don't have to rely on GitHub forks. 
I am willing to create the submission with your permission. 
Thank you for your attention. 

Best,
Marcel

**Comment by bergant** [comment]
Thanks for offering your help here - please, do as you see fit. I can also add you to collaborators on this project if needed.

**Comment by LiNk-NY** [comment]
Hi Darko, @bergant 
Please see #14 :tada:
